[package]
name = "rust-chat-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.38.1", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
futures = "0.3.30"
fastrand = "2.0.1"
compact_str = "0.7.1"